services:
  core:
    image: ghcr.io/pi-coffeebreak/core:latest
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - DATABASE_URI=${DATABASE_URI}
      - MONGODB_URI=${MONGODB_URI}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - database
      - keycloak
      - mongodb

  event-app:
    image: ghcr.io/pi-coffeebreak/event-app:latest
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_WS_URL=${VITE_WS_URL}
      - VITE_VAPID_PUBLIC_KEY=${VITE_VAPID_PUBLIC_KEY}

  frontend:
    image: ghcr.io/pi-coffeebreak/admin-frontend:latest
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_KEYCLOAK_URL=${VITE_KEYCLOAK_URL}
      - VITE_KEYCLOAK_CLIENT_ID=coffeebreak-client

  database:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:8.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${KC_DB_USERNAME}
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
    ports:
      - "5433:5432"

  mq:
    image: rabbitmq:4.0.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"

  nginx:
    image: nginx:1.27.4-alpine3.21-perl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - core
      - event-app
      - frontend 